apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-dotnet
spec:
  # setting replicas desired state in manifest will disable temporary dynameic scaling by `kubectl scale` command 
  # in production env, update this replicas value in manifest file and then use `kubectl apply` to scale pod up/down
  replicas: 4
  selector:
    matchLabels:
      app: skaffold-dotnet
  template:
    metadata:
      labels:
        app: skaffold-dotnet
    spec:
      containers:
        - name: hello-containers
          image: localhost:5000/skaffold-dotnet-hello:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5001
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "16Mi"
              cpu: "10m"
        - name: world-container
          image: localhost:5000/skaffold-dotnet-world:v0.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          env:
            - name: POD_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: SECRET_DUMMY
              valueFrom:
                secretKeyRef:
                  name: skaffold-dotnet-secret 
                  key: dummy
                  
          # Simulate same key loaded from different config map approach
          envFrom:
            - configMapRef:
                name: skaffold-dotnet-configmap-env
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: secret-volume
              mountPath: /etc/secret
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "32Mi"
              cpu: "25m"
      volumes:
        - name: config-volume
          configMap:
            name: skaffold-dotnet-configmap-mount
        - name: secret-volume
          secret:
            secretName: skaffold-dotnet-secret