apiVersion: v1
kind: Service
metadata:
  name: skaffold-dotnet
spec:
  type: LoadBalancer
  selector:
    app: skaffold-dotnet
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  sessionAffinity: None   # Set sessionAffinity to "None" to disable session affinity